// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5KmplzC_eq1sX--sJym_CMoAF',
    appId: '1:38108620:ios:f6b8fe6024f27dee32e274',
    messagingSenderId: '38108620',
    projectId: 'astroway-diploy',
    storageBucket: 'astroway-diploy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5KmplzC_eq1sX--sJym_CMoAF',
    appId: '1:38108620:ios:f6b8fe6024f27dee32e274',
    messagingSenderId: '38108620',
    projectId: 'astroway-diploy',
    storageBucket: 'astroway-diploy.appspot.com',
    iosBundleId: 'com.astrowaypro.astrologer',
  );
}
